version: '3.8'

services:
  calendar-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendar-notebook
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATA_FILE=/app/data/data.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 资源限制 - 适合低配置服务器
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    networks:
      - calendar-network

networks:
  calendar-network:
    driver: bridge

volumes:
  calendar-data:
    driver: local
  calendar-backups:
    driver: local